
CREATE TABLE USSLEVEL(/*TABLA DE NIVELES*/
	USSIDLEVEL		SERIAL PRIMARY KEY NOT NULL,																--ID DEL NIVEL
	USSDESC			VARCHAR(50) NOT NULL,																		--DESCRIPCION DEL NIVEL NOMBRE
	USSPOINT		INT NOT NULL,																				--PUNTOS PARA EL NIVEL, SI EN PUNTO TERMINA EN 0 ES USUARIO SI NO ES EMPLEADO 
	USACTIV			BOOLEAN DEFAULT TRUE NOT NULL,																--LEVEL ACTIVO
	USCOMMEN		TEXT																						--COMENTARIO DEL LEVEL
);
select * from usslevel u order by ussidlevel ;
--HACER UNA VALIDACION PARA REINICIAR EL NIVEL DEL USUARIO ? O SOLO DEL EMPLEADO?

create table SNGCLBUSINESS(/*TABLA DE LA EMPRESA CLIENTE*/
	IDBUSINESS		SERIAL PRIMATY key not null,																--ID DE LA EMPRESA
	SSBUSINAME		VARCHAR(100) not null,																		--RAZON SOCIAL
	SBUSINNUM		VARCHAR(100) null,																			--RUT O NUMERO DE LA EMPRESA
	USSPOINTS		INT DEFAULT 0 NOT NULL,																		--CANTIDAD DE PUNTOS DEL USUARIO
	USSMAIL			VARCHAR(100) UNIQUE NOT NULL,																--CORREO
	USPHONE			VARCHAR(20) NULL,																			--NUMERO TELEFONICO
	USSDATEAC		DATE DEFAULT current_timestamp NOT null,													--FECHA DE CREACION DE LA CUENTA
	USSACTIVE		BOOLEAN DEFAULT TRUE NOT NULL
	--STURNBUSIN		VARCHAR(100) NULL
);

create table SNBUSTURNLABEL(/*GIROS DE LA EMPRESA*/
	IDTURNLAB		SERIAL primary key not null,
	IDBUSINESS		INT not null,
	SIDLABEL		INT NOT NULL,																				--gIROS DE LA EMPRESA EN LA TABLA CAT LABEL
	CONSTRAINT PURCH_WAYTPAY FOREIGN KEY (SIDLABEL) REFERENCES SSNLABEL(SIDLABEL)
)

CREATE TABLE SNGBUYERUSER(/*TABLA DEL USUARIO*/
	IDBUYERUS		SERIAL PRIMARY KEY NOT NULL,																--ID DEL USUARIO
	USSUSER			VARCHAR(100) NOT NULL,																		--NOMBRE DE USUARIO
	USSNAME			VARCHAR(100) NOT NULL,																		--NOMBRES DE PILA DEL USUARIO
	USSLAST			VARCHAR(100) NOT NULL,																		--APELLIDOS DEL USUARIO
	USSPOINTS		INT DEFAULT 0 NOT NULL,																		--CANTIDAD DE PUNTOS DEL USUARIO
	USSMAIL			VARCHAR(100) UNIQUE NOT NULL,																--CORREO
	USPHONE			VARCHAR(20) NULL,																			--NUMERO TELEFONICO
	USSDATEBIR		DATE NULL,																					--FECHA DE NACIMIENTO
	USSDATEAC		DATE DEFAULT current_timestamp NOT null,													--FECHA DE CREACION DE LA CUENTA
	USSACTIVE		BOOLEAN DEFAULT TRUE NOT NULL
);
select * from "SmartNewGen".sngbuyeruser s ;

CREATE TABLE SEMPLOYEESNG(/*TABLA DEL EMPLEADO*/
	SIDEMPLOYEE		SERIAL PRIMARY KEY NOT NULL,																--ID EMPLEADO
	SEMPLNAME		VARCHAR(100) NOT NULL,																		--NOMBRES DEL EMPLEADO
	SEMPLASTN		VARCHAR(100) NOT NULL,																		--APRELLIDOS DEL EMPLEADO
	SIDLABEL		INT NOT NULL,																				--PUESTO DE TRABAJO SERÃƒï¿½ ATRAVÃƒâ€°Z DE LAS ETIQUETAS
	SDATEARRI		DATE,																						--FECHA DE LLEGADA
	SDATECONTR		DATE,																						--FECHA CUANDO SE LE DIÃƒâ€œ EL CONTRATO
	USEPOINTS		INT DEFAULT 0 NOT NULL,																		--CANTIDAD DE PUNTOS DEL EMPLEADO
	SSEMPMAIL		VARCHAR(100) UNIQUE NOT NULL,																--CORREO
	SSNUMBER		VARCHAR(20),																				--NUMERO TELEFONICO
	SSEMPDATEBIR	DATE NOT NULL,																				--FECHA DE NACIMIENTO
	--SEMSALARY		MONEY NOT NULL,																				--SALARIO DEL EMPLEADO SERA ATRAVEZ DEL COMENTARIO DE LA ETIQUETA POR PUESTO DE TRABAJO
	CONSTRAINT PURCH_WAYTPAY FOREIGN KEY (SIDLABEL) REFERENCES SSNLABEL(SIDLABEL)
);
ALTER SEQUENCE ssnlabelcateg_sidlabcat_seq RESTART WITH 100000 INCREMENT BY 1;
select * from SEMPLOYEESNG;

CREATE TABLE USSLEVEL_BUYERUS(/*TABLA PARA DELIMITAR EL NIVEL DEL USUARIO Y EMPLEADO*/
	IDUSLBUYUS		SERIAL PRIMARY KEY NOT NULL,
	USSIDLEVEL		INT, 				--ID DEL NIVEL DEL USUARIO 
	IDBUYERUS		INT, 				--ID DEL NIVEL DEL USUARIO 
	CONSTRAINT LEVEL_USER FOREIGN KEY (USSIDLEVEL) REFERENCES USSLEVEL (USSIDLEVEL),
	CONSTRAINT BUYER_USER FOREIGN KEY (IDBUYERUS) REFERENCES SNGBUYERUSER (IDBUYERUS)
);
select* from usslevel_buyerus ub ;
ALTER TABLE USSLEVEL_BUYERUS ADD COLUMN SIDEMPLOYEE INT;
alter table USSLEVEL_BUYERUS add constraint LEVEL_EMPL foreign key (SIDEMPLOYEE) references SEMPLOYEESNG (SIDEMPLOYEE);

CREATE TABLE USCCOUNTRY(/*TABLA DE PAISES*/
	IDCCOUNTRY		SERIAL PRIMARY KEY NOT NULL,																--ID DEL PAIS
	SNCODE			CHAR(3) UNIQUE NOT NULL,																	--CODIGO DEL PAIS
	SNCOUNTRY		VARCHAR(50) UNIQUE NOT NULL,  																--NOMBRE DEL PAIS
	SNCODNUM		VARCHAR(5)	null,																			--CODIGO DE PAIS PARA NUMERO DE CELULAR
	SNMONEY 		CHAR(3) null,																				--Nombre de la moneda Digital
	SNSYMBOL 		VARCHAR(4) null,																			--Simbolo de la moneda
	SNDESSYM		VARCHAR(30) 																				--Nombre de la moneda fisica
);
select * from usccountry u order  by idccountry ;

CREATE TABLE SNGCITY(/*TABLA DE CIUDADES*/
	IDSNGCITY 		SERIAL PRIMARY KEY NOT NULL,																--ID DE LA CUIDAD
	IDCCOUNTRY		INT,																						--PAIS
	SMDESCITY		VARCHAR(100) NOT null, 																		--NOMBRE DE LA CUIDAD
	CONSTRAINT CITY_COUNTRY FOREIGN KEY (IDCCOUNTRY) REFERENCES USCCOUNTRY (IDCCOUNTRY)
);
select * from SNGCITY;

CREATE TABLE SNGADDRES(/*DIRECCION ACTIVA*/
	IDSNGADDR		SERIAL PRIMARY key not NULL,																--ID DE LA DIRECCION
	IDBUYERUS		INT NOT NULL,																				--ID DEL USUARIO
	SNNAMEADDR		VARCHAR(100) NOT NULL,																		--Nombre de referencia de la dirección
	IDSNGCITY		INT NOT NULL,																				--ID DE LA CUIDAD
	SNADDRDES		VARCHAR(100) NOT NULL,																		--DIRECCION REAL
	SNNUMADDR		INT NOT null,																				--Numero de dirección
	SNDPHOADDR		INT NULL, 																					--Numero del departamento o casa
	SNGDATEADD		timestamp DEFAULT current_timestamp NOT NULL,												--FECHA EN LA QUE SE INGRESÃƒâ€œ
	SNGACTIVE		BOOLEAN DEFAULT TRUE NOT NULL,																--DIRECCION ACTIVA
	SNGPPREFE		BOOLEAN DEFAULT false NOT null,																--Direccion que cargara siempre por defecto si hay mas direcciones activas
	SNGCADCOMM		TEXT,																						--COMENTARIOS DE LA DIRECCION
	sidlabcat 		INT NULL;																				--EL TIPO INDICARA QUE TIPO DE DIRECCION (DIRECCION FISICA, TELEFONO, CORREO, TELEFONO FIJO ETC)
	CONSTRAINT IDUSER_ADDRESS FOREIGN KEY (IDBUYERUS) REFERENCES SNGBUYERUSER (IDBUYERUS),
	CONSTRAINT IDCITY_ADDRESS FOREIGN KEY (IDSNGCITY) REFERENCES SNGCITY (IDSNGCITY),
	CONSTRAINT CAT_TAG FOREIGN KEY (SIDLABEL) REFERENCES SSNLABEL(SIDLABEL)
);
select * from SNGADDRES;

CREATE TABLE SSNLABEL(--ETIQUETA 	
	SIDLABEL		SERIAL PRIMARY key not NULL,														 		--ID ETIQUETA
	SLABDESC		VARCHAR(50) UNIQUE NOT NULL,															 	--DESCRIPCION NOMBRE
	SLABACTIV		BOOLEAN DEFAULT TRUE NOT NULL,																--ETIQUETA ACTIVA
	SLABCOMM		TEXT																					 	--COMENTARIO
);
ALTER SEQUENCE usslevel_ussidlevel_seq RESTART WITH 1000 INCREMENT BY 10;

CREATE TABLE SSNLABELCATEG(--CATEGORIA DE LA ETIQUETA 	
	SIDLABCAT		SERIAL PRIMARY key NOT NULL,														 		--ID CATEGORIA DE LA ETIQUETA
	SIDLABEL		INT not NULL,				 																--ETIQUETA
	SLABCATDESC		VARCHAR(50) UNIQUE NOT NULL,															 	--DESCRIPCION NOMBRE
	SLAACTIV		BOOLEAN DEFAULT TRUE NOT NULL,																--CATEGORIA DE LA ETIQUETA ACTIVA
	SLACACOMM		text,																					 	--COMENTARIO
	CONSTRAINT CAT_TAG FOREIGN KEY (SIDLABEL) REFERENCES SSNLABEL(SIDLABEL)
);
ALTER SEQUENCE ssnlabelcateg_sidlabcat_seq RESTART WITH 1000 INCREMENT BY 10;
select * from ssnlabelcateg s ;

CREATE TABLE US_PWD(--ADMINISTRADOR DE PASSWORD
	IDUSSPWD			SERIAL PRIMARY KEY NOT NULL,																--ID DE LA PASS ACTIVA
	IDBUYERUS		INT  NULL,																					--ID DEL USUARIO PUEDE SER NULL
	SIDEMPLOYEE		INT NULL,																					--ID DEL EMPLEADO PUEDE SER NULL
	USSPWD			VARCHAR(255) NOT NULL,																		--CONTRASENA ACTIVA REAL SHA-15
	USPWDCHACT		BOOLEAN DEFAULT TRUE NOT NULL,																--HABILITAR DE CAMBIO DE CONTRASEÑA
	USSDATE			TIMESTAMP NOT NULL,																			--FECHA CUANDO EXPIRA LA PASS
	USALERTCH		INT NOT NULL default 5,																		--FECHA QUE SE MOSTRARA EL ALERT PARA AVISAR QUE DEBE CAMBIAR LA CONSTRASEÑA X DIAS ANTES
	USPWDCHANGE		INT NOT NULL default 90,																	--CADA CUANTO TIEMPO SE CAMBIA, SI ESTA ACTIVO CADA X DIAS EXPIRARA
	UDPWDINIT		TIMESTAMP DEFAULT current_timestamp NOT null,												--FECHA CUANDO SE INGRESO POR PRIMERA VEZ
	USSDATLAST		TIMESTAMP NULL,																				--FECHA CUANDO SE UPDATEO POR ULTIMA VEZ
	USSACTIV		BOOLEAN DEFAULT TRUE NOT null,																--1 ACTIVE 0 INACTIVE
	CONSTRAINT USER_PWDACTV FOREIGN KEY (IDBUYERUS) REFERENCES SNGBUYERUSER (IDBUYERUS),
	CONSTRAINT IDUSER_PWDACTV FOREIGN KEY (SIDEMPLOYEE) REFERENCES SEMPLOYEESNG(SIDEMPLOYEE)
);
ALTER SEQUENCE ssnlabelcateg_sidlabcat_seq RESTART WITH 10 INCREMENT BY 10;

CREATE TABLE SSALEPROD(/*PRODUCTOS*/
	SSAIDPROD		SERIAL PRIMARY KEY NOT NULL,																--ID PRODUCTO
	SSABACODE		VARCHAR(50) NOT NULL,																		--CODIGO DE BARRA
	SSAPRODESC		VARCHAR(100) NOT NULL,																		--DESCRIPCION DEL PRODUCTO
	SSAACTIVE		BOOLEAN DEFAULT TRUE NOT NULL,																--PRODUCTO ACTIVO 1 ACTIVE
	SSDATEADD		TIMESTAMP DEFAULT current_timestamp NOT NULL,												--FECHA EN LA QUE FUE AGREGADO
	SSPOINTPR		INT NULL,																					--PUNTOS QUE SUMARÃ� EL USUARIO POR ESTE PRODUCTO
	SSCOMMENP		TEXT																						--COMENTARIOS PARA EL PRODUCTO
);
ALTER SEQUENCE ssaleprod_ssaidprod_seq RESTART WITH 100000 INCREMENT BY 100;
select * from SSALEPROD;

CREATE TABLE SLABELPROD (/*ETIQUETAS PARA LOS PRODUCTOS CATEGORIAS Y CARACTERISTICAS*/
	SIDLABPRD		SERIAL PRIMARY KEY NOT NULL,																--ID ETIQUETAS DEL PRODUCTO
	SSAIDPROD		INT  NOT NULL,																				--ID PRODUCTO
	SIDLABCAT		INT  NOT NULL,																				--CATEGORIA DE ETIQUETAS
	SSAPRDPRICE		MONEY NOT NULL,																				--PRECIO VENTA
	CONSTRAINT PRODID_LAB FOREIGN KEY (SSAIDPROD) REFERENCES SSALEPROD(SSAIDPROD),
	CONSTRAINT LABCAT_PROD FOREIGN KEY (SIDLABCAT) REFERENCES SSNLABELCATEG(SIDLABCAT)
);
select * from SLABELPROD;

CREATE TABLE SNWAREH(/*BODEGA*/	
	SIDWAREH		SERIAL PRIMARY KEY NOT NULL,																--ID BODEGA
	SWARDESC		VARCHAR(100) NOT NULL,																		--NOMBRE DESCRIPCION
	SWARADDR		VARCHAR(100) NOT NULL,																		--DIRECCION
	SWARACTIV		BOOLEAN DEFAULT TRUE NOT NULL,																--BODEGA ACTIVA
	SWADATE			TIMESTAMP DEFAULT current_timestamp NOT NULL,												--FECHA EN QUE FUE INGRESADO
	SNWCOMMEN		TEXT																						--COMENTARIO PARA LA BODEGA
);

ALTER SEQUENCE snwareh_sidwareh_seq RESTART WITH 100 INCREMENT BY 1;

CREATE TABLE SSPRSTORE(/*TIENDA*/) inherits (SNWAREH);
select * from SSPRSTORE;

CREATE TABLE SPRDWAREH(/*TABLA PRODUCTOS EN BODEGAS*/
	SIDPDDWAR		SERIAL PRIMARY KEY NOT NULL,																--IDPRODXBODE
	SIDWAREH		INT NOT NULL,																				--ID BODEGA
	SIDPRVPRD		INT NOT NULL,																				--ID PRODUCTOS DEL PROVEEDOR
	SPDWACURQ		INT DEFAULT 0 NOT NULL,																		--CANTIDAD ACTUAL
	SPDWAMINQ		INT DEFAULT 50 NOT NULL,																	--CANTIDAD MINIMA
	SPDWAMAXQ		INT DEFAULT 100 NOT NULL,																	--CANTIDAD MAXIMA
	SPDWACOMM		TEXT,																						--COMENTARIOS DE LOS PRODUCTOS EN BODEGA
	SDATEADD		TIMESTAMP DEFAULT current_timestamp NOT NULL
	CONSTRAINT PRODXWIREHOUSE FOREIGN KEY (SIDWAREH) REFERENCES SNWAREH(SIDWAREH),
	CONSTRAINT PRODIDXPROV FOREIGN KEY (SIDPRVPRD) REFERENCES SPROV_PROD(SIDPRVPRD)
);
ALTER SEQUENCE sprdwareh_sidpddwar_seq RESTART WITH 1000 INCREMENT BY 10;
select * from SPRDWAREH;

CREATE TABLE SPRD_STORE(/*TABLA PRODUCTOS EN TIENDAS*/
	SIDPRXSTR		SERIAL PRIMARY KEY NOT NULL,																--ID PRODXTIENDA
	SIDWAREH		INT NOT NULL,			 																	--ID TIENDA
	SIDPDDWAR		INT NOT NULL,																				--ID PRODUCTOS EN BODEGA
	SPDSTCURQ		INT DEFAULT 0 NOT NULL,																		--CANTIDAD ACTUAL
	SPDSTMINQ		INT DEFAULT 50 NOT NULL,																	--CANTIDAD MINIMA
	SPDSTMAXQ		INT DEFAULT 100 NOT NULL,																	--CANTIDAD MAXIMA
	SPRDSTCOMM		TEXT,																						--COMENTARIOS DE LOS PRODUCTOS EN TIENDA
	SDATEADD		TIMESTAMP DEFAULT current_timestamp NOT NULL,
	CONSTRAINT PRODX_STORE FOREIGN KEY(SIDWAREH) REFERENCES SSPRSTORE(SIDWAREH),
	CONSTRAINT PROD_STORE FOREIGN KEY (SIDPDDWAR) REFERENCES SPRDWAREH(SIDPDDWAR)
);
select * from SPRD_STORE;

CREATE TABLE SBUPROVIDE(/*TABLA PROVEEDORES*/
	SIDBUPRV		SERIAL PRIMARY KEY,																			--ID PROVEEDOR
	SBPRVRUT		VARCHAR(20) UNIQUE NOT NULL,																--RUT
	SBPRVCHD		CHAR(1) NOT NULL,																			--DIGITO VERIFICADOR
	SBUPRVNAME		VARCHAR(50) NOT NULL,																		--RAZON SOCIAL
	SBUPRVGIRO		VARCHAR(100),																				--GIRO
	SBUPRVNUMBER	VARCHAR(15),																				--NUMERO
	SPROVADDRESS	TEXT,																						--DIRECCIÃƒâ€œN DE LA EMPRESA
	SPROVDATE		TIMESTAMP DEFAULT current_timestamp NOT null,												--FECHA EN LA QUE FUE INGRESADO
	SPROVCOMM		TEXT NULL																					--Comentarios para el proveedor
);
ALTER SEQUENCE sbuprovide_sidbuprv_seq RESTART WITH 1000 INCREMENT BY 10;
select * from sbuprovide s ;

CREATE TABLE SPROVICONTACT(/*CONTACTO DE PROVEEDORES*/
	SIDCONTACT 		SERIAL PRIMARY KEY NOT NULL,																--ID DEL CONTACTO
	SIDBUPRV		INT NOT NULL,				 																--ID DEL PROVEEDOR
	SCONTNAME		VARCHAR(100) NOT NULL,																		--NOMBRE DEL CONTACTO
	SCONTNUMER		VARCHAR(15)  NULL,																			--NUMERO TELEFONICO
	SCONTEMAIL		VARCHAR(100) NULL,																			--CORREO DEL CONTACTO
	SCONTADDRESS	TEXT,																						--DIRECCIÃƒâ€œN DEL CONTACTO
	SCONTACTIV		BOOLEAN DEFAULT TRUE NOT NULL,																--CONTACTO ACTIVO
	SCONTDATEI		TIMESTAMP DEFAULT current_timestamp NOT null,												--FECHA EN LA QUE FUE INGRESADO
	SPROVCCOMM		TEXT NULL,																					--Comentarios para el proveedor
	CONSTRAINT PROV_CONTACT FOREIGN KEY (SIDBUPRV) REFERENCES SBUPROVIDE(SIDBUPRV)
);
ALTER SEQUENCE sprovicontact_sidcontact_seq RESTART WITH 1000 INCREMENT BY 10;

CREATE TABLE SPROV_PROD(/*PRODUCTOS DEL PROVEEDOR*/
	SIDPRVPRD		SERIAL PRIMARY KEY NOT NULL,																--ID PRODXPROVEE
	SIDBUPRV		INT  NOT NULL,																				--ID PROVEEDOR
	SIDLABPRD		INT  NOT NULL,																				--ID DE CATEGORIA DE PRODUCTO
	SPVXPDPRICE		MONEY NULL,																			 		--PRECIO COMPRA
	SSAPVPDCOMM		TEXT,																					 	--COMENTARIO
	SDATEADD		TIMESTAMP DEFAULT current_timestamp NOT NULL,
	CONSTRAINT PROD_CONTACT FOREIGN KEY (SIDBUPRV) REFERENCES SBUPROVIDE(SIDBUPRV),
	CONSTRAINT CATE_PROD FOREIGN KEY (SIDLABPRD) REFERENCES SLABELPROD(SIDLABPRD)
);
ALTER SEQUENCE sprov_prod_sidprvprd_seq RESTART WITH 1000 INCREMENT BY 10;
select * from SPROV_PROD;

CREATE TABLE SAMPURPAY(/*CANTIDAD DE PAGOS PARA REALIAR LA COMPRA*/
	IDAMPURPAY SERIAL primary key not null,--ID CANTIDAD DE PAGOS
	--ID DE LA COMPRA DEL CLIENTE,
	--ID DE ETIQUETAS DE TIPO DE PAGO
	--CANTIDAD QUE PAGA POR ESTE TIPO DE PAGO MONEY (SI ES EN DOLARES, PREVIAMENTE SE DEBE REALIZAR LA CONVERCI�N A PESO CHILENO)
																		
);

CREATE TABLE SNPURCHUS(/*COMPRAS DEL USUARIO*/
	SNIDPURCHUS		INT IDENTITY(10000, 1) PRIMARY KEY NOT NULL,												--ID COMPRAS DEL USUARIO
	IDINVOICE		VARCHAR(50) NULL,																			--ID DE LA FATCTURA, ESTA LLEGARA YA RELIZADA POR EL SISTEMA DE FACTIURACION SE DEBE INGRESAR LUEGO
	IDTICKET		VARCHAR(50) NULL,																			--ID DE LA BOLETA = = = = =
	IDUSSHOP		INT  NOT NULL,																				--ID DEL USUARIO
	SNDATEPUR		TIMESTAMP DEFAULT current_timestamp NOT NULL,												--FECHA DE LA COMPRA
	STOTALQUAN		INT NOT NULL,																				--CANTIDAD TOTAL DE LA COMPRA
	STOTVALUE		MONEY NOT NULL,																				--VALOR TOTAL DE LA COMPRA
	SDISCOUNT		NUMERIC(10, 2)	DEFAULT 0,																	--DESCUENTO total
	SPURCHACT		BOOLEAN default true not null,																--FACTURA O BOLETA ACTIVA
	CONSTRAINT IDUSER_PURCH FOREIGN KEY (IDUSSHOP) REFERENCES USSHOP
);
ALTER SEQUENCE sprov_prod_sidprvprd_seq RESTART WITH 1000 INCREMENT BY 10;

CREATE TABLE SNDETAILPURCH(/*DETALLE DE LA COMPRA*/
	SIDDETAILPUR	INT IDENTITY(100000, 1) PRIMARY KEY NOT NULL,												--ID DETALLE DE COMPRA DEL USUARIO
	SNIDPURCHUS		INT CONSTRAINT DETAIL_PURCH FOREIGN KEY (SNIDPURCHUS) REFERENCES SNPURCHUS NOT NULL,		--ID DE LA COMPRA
	SIDLABPRD		INT CONSTRAINT DETA_PROD FOREIGN KEY (SIDLABPRD) REFERENCES SLABELPROD(SIDLABPRD),						--ID PRODUCTO
	SPRODIVA		INT NULL,																					--IVA DEL PRODUCTO
	SDETAILQUAN		INT NOT NULL,																				--CANTIDAD DETALLE DE LA COMPRA
	SPARCIALTOTAL	INT NOT null,																				--SUBTOTAL DETALLE DE LA COMPRA
	SDETAIACTV		BOOLEAN default true not null																--VERIFICA SI EL PRODUCTO DE ESTA VENTA AUN SIGUE VIGENTE O SE CANCELO SOLO 1 PROD EN ESPECIFICO
);


/*EN LA INTERFAZ GRAFICA SE DEBERA BUSCAR EL ID DE LA COMPRA, SE LE DARA A MODIFICAR Y SELECCIONARA EL O LOS PRODUCTOS
 * (SI SELECCIONA TODOS, AUTOMATIC, ANULA LA BOLETA O FACTURA)
 * SE LE DARA EL MOTIVO POR EL CUAL SE REALIZA NOTA O POR CAMBIO DE PROD O DEVOLICION DEL DINERO
 * SI SE HACE UN CAMBIO DE PRODUCTO, ESTE SE DEBE DESCONTAR DEL STOCK SI EL PRODUCTO TIENE UN PRECIO MAYOR AUTOM. SE SABRA QUE ES UNA NOTA DE DEBITO DE LO CONTRARIO
 * ES UNA NOTA DE CREDITO
 * SI SOLICITA UN CAMBIO DE VARIAS UNIDADES DEL MISMO PRODUCTOS SE DEBE INDICAR CUAANTAS CAMBIA Y CUANTA QUIERE A FAVOR, ESTO SE DEBE TENER EN CUENTA EL STOCK DE ESTE PRODUCTO
 *  
 * SI SE HACE UNA DEVOLUCION DEL PRODUCTO, SE DEBE DESCONTA EL TOTAL DE LA CAJA EL TOTAL DE PRODUCTO YA COMPRADO
 * Y SI EL PRODUCTO ESTA EN BUENAS CONDICIONES SE SUMA AL STOCK EN VENTA (ESTO SE SABRA PORQUE LA NOTA DE CRED Y DEB YA VENDRA DEFINIDO)
 * 
 * 
 * TABLA nota de credito - DEBITO DEL CLIENTE
 * IDNOTA SERIAL PRIAMRY KEY
 * NUMnotaCREDITO VARCHAR NULL SI ES NOTA DE CREDITO
 * NUMNOTADEBITO VARCHAR NULL  SI ES NOTA DE DEBITO
 * id deL DETALLE DE LA compra DEL USUARIO(LUEGO SE BUSCARA POR ID DE LA COMPRA)
 * ID DE LA CATEGORIA DEL PRODUCTO QUE SE HACE EL CAMBIO PARA LUEGO HACER EL DESCUENTO NULL
 * MONTO DE LA NOTA DE CREDITO O DEBITO POSITIVO O NEGATIVO
 * DETALLE DE LA NOTA - SI FUE UN CAMBIO . DEVOLUCI�N - 
 * FECHA EN LA CUAL SE INGRES�
 * COMENTARIO DE LA NOTA DE CREDITO O DEBITO (PRODUCTO DA�ADO O PRODUCTO NO CORRESPONDIA A LO COMPRADO ETC)
 * */


/*
 * ID DEL DETALLE DE LA COMPRA AL PROVEEDOR
 * 
 * */



--VERIFICAR SI SE CREARA OTRA TABLA PARA INDICAR LA CANTIDAD DE DESCUENTPS QUE TUVO AL COMPRAR
--SE AGREGARA EN LA MISMA TABLA DE VENTAS LA FORMA DE PAGO Y EL ESTADO DE LA COMPRA


--syso para imprimir en java con eclipse

create table SNGHISTORYAUDIT(
	IDHISAUD		VARCHAR(10) primary key not null,
	IDBUYERUS		INT not null,
	HISAUDDESC		text not null,
	DATEHISAU		TIMESTAMP DEFAULT current_timestamp NOT NULL,
	CONSTRAINT BUYER_USER FOREIGN KEY (IDBUYERUS) REFERENCES SNGBUYERUSER (IDBUYERUS)
);
 

select * from sngaddres ;

ALTER TABLE USCCOUNTRY ALTER COLUMN SNSYMBOL TYPE VARCHAR(4);
ALTER SEQUENCE teams2_id_seq RESTART WITH 3 INCREMENT BY 3;
ALTER SEQUENCE teams_id_seq RESTART WITH 31;
--ALTER TABLE USCCOUNTRY ADD COLUMN USSYMBOL CHAR(1);

drop table usccountry ;

/*CREAR UN TRIGER PARA AUMENTAR LOS PUNTOS INTERMEDIOS*/
drop table USSLEVEL;
drop table SNGBUYERUSER;

select * from usslevel u ;
insert into usslevel (ussdesc , usspoint , uscommen) VALUES('Novato', 10, '');
insert into usslevel (ussdesc , usspoint , uscommen) VALUES('Comprador', 50, '');
insert into usslevel (ussdesc , usspoint , uscommen) VALUES('Apasionado', 200, '');
insert into usslevel (ussdesc , usspoint , uscommen) VALUES('Profesional', 500, '');
insert into usslevel (ussdesc , usspoint , uscommen) VALUES('Estrella', 1000, '');
insert into usslevel (ussdesc , usspoint , uscommen) VALUES('Maestro de la Compra', 9999999, '');

SELECT current_timestamp;