spring:
  application:
    name: "SmartNewGenApi"
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 30
  hibernate:
    ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: admin
    hikari:
      data-source-properties:
        useServerPrepStmts: true
        cachePrepStmts: true

server: 
  port: 8030
  tomcat:
    mbeanregistry:
      enabled: true

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace